#!/bin/sh

picom --experimental-backends &
feh --no-fehbg --bg-fill $HOME/downloads/wallpaper.png &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width 0
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config gapless_monocle true
bspc config single_monocle true
